#!/bin/bash

set -e -o pipefail

IMAGE_NAME="${IMAGE_NAME?Not found in environment}"

version_arg="${1-}"

if [[ ! "${version_arg}" ]]
then
    printf "First argument must be a version string of the form \"<major>.<minor>.<patch>-<rev>\". Exiting.\\n"
    exit 1
fi

full_version="${version_arg}"
version="$(printf "%s" "${full_version}" | cut -d"." -f1-3)"
minor="$(printf "%s" "${version}" | cut -d"." -f1-2)"

for tag in latest ${full_version} ${version} ${minor}
do
    printf "%s:%s," "${IMAGE_NAME}" "${tag}"
done
