#!/bin/bash

set -euv -o pipefail

ARCH="${1:?Missing in environment}"

dockerfile="Dockerfile.${ARCH}"

# Build image
if [ "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]
then
    case "${ARCH}" in
        "amd64") arch_tag="" ;;
        *) arch_tag="-${ARCH}" ;;
    esac

    git_tag=$(git describe --abbrev=0);
    latest_tag="latest${arch_tag}";

    docker build -t "${DOCKER_IMAGE}:${latest_tag}" -f "${dockerfile}" .;
    ./scripts/image_tag "${git_tag}";
else
    docker build -t "${DOCKER_IMAGE}:develop-${ARCH}" -f "${dockerfile}" .;
fi

# List images
docker images
