name: "PR"

on:
  pull_request:
    branches:
      - "master"

env:
  IMAGE_NAME: "nventiveux/syncthing"
  DOCKER_BUILDKIT: "1"

jobs:
  lint:
    name: "Linting"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Lint Dockerfile"
        uses: "hadolint/hadolint-action@v3.0.0"
        with:
          dockerfile: "Dockerfile"

  build:
    name: "Build"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "amd64,arm64,arm"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"
        with:
          install: true

      - name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: "Build images"
        uses: "docker/build-push-action@v3"
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          context: "."
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
          push: true
          tags: "${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}"
