name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Docker image"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: write
    env:
      IMAGE_NAME: "nventiveux/syncthing"
      DOCKER_BUILDKIT: "1"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "amd64,arm64,arm"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"
        with:
          install: true

      - name: "Prepare"
        id: "prep"
        run: |
          tags="$(scripts/image-tag "${GITHUB_REF##refs/tags/v}")"
          echo "image_tags=${tags}" >> $GITHUB_OUTPUT

      - name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: "Build images"
        uses: "docker/build-push-action@v3"
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          context: "."
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
          push: true
          tags: "${{ steps.prep.outputs.image_tags }}"

      - name: "Update Docker Hub's README"
        uses: "peter-evans/dockerhub-description@v3"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: "${{ env.IMAGE_NAME }}"

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
