name: "Release ARM32V6"

on:
  push:
    branches:
      - "develop"
    tags:
      - v*

jobs:
  docker_image:
    name: "Docker image"
    runs-on: "ubuntu-20.04"
    env:
      ARCH: "arm32v6"
      IMAGE_NAME: "nventiveux/syncthing"
      DOCKER_BUILDKIT: "1"
      QEMU_VERSION: "4.0.0-2"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install QEMU"
        run: |
          ./scripts/install-qemu

      - name: "Build unstable image"
        if: ${{ success() && startsWith(github.ref, 'refs/heads/') }}
        run: |
          version="$(date +%Y.%m.%d)"
          branch_name="${GITHUB_REF#refs/heads/}"

          docker run \
            --rm \
            --privileged \
            multiarch/qemu-user-static:register --reset

          docker build \
            -t ${IMAGE_NAME}:${branch_name}-${ARCH} \
            -t ${IMAGE_NAME}:${branch_name}-${version}-${ARCH} \
            -f Dockerfile.${ARCH} .

          docker images

      - name: "Build stable image"
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        run: |
          version="${GITHUB_REF#refs/tags/v}"

          docker run \
            --rm \
            --privileged \
            multiarch/qemu-user-static:register --reset

          docker build \
            -t ${IMAGE_NAME}:latest-${ARCH} \
            -f Dockerfile.${ARCH} .

          ./scripts/image_tag "${version}"

          docker images

      - name: "Push image"
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push --all-tags ${IMAGE_NAME}
          docker logout

      - name: "Update Docker Hub's README"
        uses: "peter-evans/dockerhub-description@v2"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: "${{ env.IMAGE_NAME }}"
