name: "Release AMD64"

on:
  push:
    branches:
      - "develop"
    tags:
      - v*

jobs:
  docker_image:
    name: "Docker image"
    runs-on: "ubuntu-20.04"
    env:
      ARCH: "amd64"
      IMAGE_NAME: "nventiveux/syncthing"
      DOCKER_BUILDKIT: "1"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Build unstable image"
        if: ${{ success() && startsWith(github.ref, 'refs/heads/') }}
        run: |
          version="$(date +%Y.%m.%d)"
          branch_name="${GITHUB_REF#refs/heads/}"

          docker build \
            -t ${IMAGE_NAME}:${branch_name} \
            -t ${IMAGE_NAME}:${branch_name}-${version} \
            -f Dockerfile.${ARCH} .

          docker images

      - name: "Build stable image"
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        run: |
          version="${GITHUB_REF#refs/tags/v}"

          docker build \
            -t ${IMAGE_NAME}:latest-${ARCH} \
            -f Dockerfile.${ARCH} .

          ./scripts/image_tag "${version}"

          docker images

      - name: "Push image"
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push --all-tags ${IMAGE_NAME}
          docker logout

      - name: "Update Docker Hub's README"
        uses: "peter-evans/dockerhub-description@v2"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: "${{ env.IMAGE_NAME }}"
